/*
 * Copyright 2014, General Dynamics C4 Systems
 *
 * This software may be distributed and modified according to the terms of
 * the GNU General Public License version 2. Note that NO WARRANTY is provided.
 * See "LICENSE_GPLv2.txt" for details.
 *
 * @TAG(GD_GPL)
 */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __API_ARCH_INVOCATION_H
#define __API_ARCH_INVOCATION_H
#include <arch/api/sel4_invocation.h>
enum arch_invocation_label {
    ARMPageTableMap = nSeL4ArchInvocationLabels,
    ARMPageTableUnmap,
#if defined(CONFIG_ARM_SMMU)
    ARMIOPageTableMap,
#endif
#if defined(CONFIG_ARM_SMMU)
    ARMIOPageTableUnmap,
#endif
    ARMPageMap,
    ARMPageUnmap,
#if defined(CONFIG_ARM_SMMU)
    ARMPageMapIO,
#endif
    ARMPageClean_Data,
    ARMPageInvalidate_Data,
    ARMPageCleanInvalidate_Data,
    ARMPageUnify_Instruction,
    ARMPageGetAddress,
    ARMASIDControlMakePool,
    ARMASIDPoolAssign,
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUSetTCB,
#endif
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUInjectIRQ,
#endif
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUReadReg,
#endif
#if defined(CONFIG_ARM_HYPERVISOR_SUPPORT)
    ARMVCPUWriteReg,
#endif
    ARMIRQIssueIRQHandlerTrigger,
#if CONFIG_MAX_NUM_NODES > 1
    ARMIRQIssueIRQHandlerTriggerCore,
#endif
    nArchInvocationLabels
};

#endif /* __API_ARCH_INVOCATION_H */
