/* generated by /home/wego/seL4test/tools/seL4/elfloader-tool/../cmake-tool/helpers/platform_sift.py BEGIN */
int num_memory_regions = 1;

struct memory_region {
    size_t start;
    size_t end;
} memory_region[1] = {
	{ .start = 268435456, .end = 4160749568 },
};
/* generated by /home/wego/seL4test/tools/seL4/elfloader-tool/../cmake-tool/helpers/platform_sift.py END */
