/*
 * Copyright 2017, Data61
 * Commonwealth Scientific and Industrial Research Organisation (CSIRO)
 * ABN 41 687 119 230.
 *
 * This software may be distributed and modified according to the terms of
 * the BSD 2-Clause license. Note that NO WARRANTY is provided.
 * See "LICENSE_BSD2.txt" for details.
 *
 * @TAG(DATA61_BSD)
 */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_INVOCATION_H
#define __LIBSEL4_INVOCATION_H

enum invocation_label {
    InvalidInvocation,
    UntypedRetype,
    TCBReadRegisters,
    TCBWriteRegisters,
    TCBCopyRegisters,
#if !defined(CONFIG_KERNEL_MCS)
    TCBConfigure,
#endif
#if defined(CONFIG_KERNEL_MCS)
    TCBConfigure,
#endif
    TCBSetPriority,
    TCBSetMCPriority,
#if !defined(CONFIG_KERNEL_MCS)
    TCBSetSchedParams,
#endif
#if defined(CONFIG_KERNEL_MCS)
    TCBSetSchedParams,
#endif
#if defined(CONFIG_KERNEL_MCS)
    TCBSetTimeoutEndpoint,
#endif
    TCBSetIPCBuffer,
#if !defined(CONFIG_KERNEL_MCS)
    TCBSetSpace,
#endif
#if defined(CONFIG_KERNEL_MCS)
    TCBSetSpace,
#endif
    TCBSuspend,
    TCBResume,
    TCBBindNotification,
    TCBUnbindNotification,
#if (!defined CONFIG_KERNEL_MCS) && CONFIG_MAX_NUM_NODES > 1
    TCBSetAffinity,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBSetBreakpoint,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBGetBreakpoint,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBUnsetBreakpoint,
#endif
#if defined(CONFIG_HARDWARE_DEBUG_API)
    TCBConfigureSingleStepping,
#endif
    TCBSetTLSBase,
    CNodeRevoke,
    CNodeDelete,
    CNodeCancelBadgedSends,
    CNodeCopy,
    CNodeMint,
    CNodeMove,
    CNodeMutate,
    CNodeRotate,
#if !defined(CONFIG_KERNEL_MCS)
    CNodeSaveCaller,
#endif
    IRQIssueIRQHandler,
    IRQAckIRQ,
    IRQSetIRQHandler,
    IRQClearIRQHandler,
    DomainSetSet,
#if defined(CONFIG_KERNEL_MCS)
    SchedControlConfigure,
#endif
#if defined(CONFIG_KERNEL_MCS)
    SchedContextBind,
#endif
#if defined(CONFIG_KERNEL_MCS)
    SchedContextUnbind,
#endif
#if defined(CONFIG_KERNEL_MCS)
    SchedContextUnbindObject,
#endif
#if defined(CONFIG_KERNEL_MCS)
    SchedContextConsumed,
#endif
#if defined(CONFIG_KERNEL_MCS)
    SchedContextYieldTo,
#endif
    nInvocationLabels
};
#include <sel4/sel4_arch/invocation.h>
#include <sel4/arch/invocation.h>

#endif /* __LIBSEL4_INVOCATION_H */
