/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_RPC_PB_H_INCLUDED
#define PB_RPC_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Action {
    Action_ALLOCATE = 0,
    Action_FREE = 1
} Action;
#define _Action_MIN Action_ALLOCATE
#define _Action_MAX Action_FREE
#define _Action_ARRAYSIZE ((Action)(Action_FREE+1))

/* Struct definitions */
typedef struct _IOPortMessage {
    uint32_t start;
    uint32_t end;
/* @@protoc_insertion_point(struct:IOPortMessage) */
} IOPortMessage;


typedef struct _IrqAllocMessageSimple {
    bool setTrigger;
    uint64_t irq;
    uint64_t trigger;
/* @@protoc_insertion_point(struct:IrqAllocMessageSimple) */
} IrqAllocMessageSimple;


typedef struct _IrqAllocMessagex86_IOAPIC {
    uint64_t ioapic;
    uint64_t pin;
    uint64_t level;
    uint64_t polarity;
    uint64_t vector;
/* @@protoc_insertion_point(struct:IrqAllocMessagex86_IOAPIC) */
} IrqAllocMessagex86_IOAPIC;


typedef struct _IrqAllocMessagex86_MSI {
    uint64_t pci_bus;
    uint64_t pci_dev;
    uint64_t pci_func;
    uint64_t handle;
    uint64_t vector;
/* @@protoc_insertion_point(struct:IrqAllocMessagex86_MSI) */
} IrqAllocMessagex86_MSI;


typedef struct _MemoryAllocMessage {
    uint64_t address;
    uint64_t size_bits;
    uint64_t type;
    Action action;
/* @@protoc_insertion_point(struct:MemoryAllocMessage) */
} MemoryAllocMessage;


typedef struct _ReturnMessage {
    uint32_t errorCode;
    uint64_t cookie;
/* @@protoc_insertion_point(struct:ReturnMessage) */
} ReturnMessage;


typedef struct _IrqAllocMessage {
    pb_size_t which_type;
    union {
        IrqAllocMessagex86_MSI msi;
        IrqAllocMessagex86_IOAPIC ioapic;
        IrqAllocMessageSimple simple;
    } type;
/* @@protoc_insertion_point(struct:IrqAllocMessage) */
} IrqAllocMessage;


typedef struct _RpcMessage {
    pb_size_t which_msg;
    union {
        ReturnMessage ret;
        MemoryAllocMessage memory;
        IrqAllocMessage irq;
        IOPortMessage ioport;
    } msg;
/* @@protoc_insertion_point(struct:RpcMessage) */
} RpcMessage;


/* Initializer values for message structs */
#define MemoryAllocMessage_init_default          {0, 0, 0, _Action_MIN}
#define IrqAllocMessagex86_MSI_init_default      {0, 0, 0, 0, 0}
#define IrqAllocMessagex86_IOAPIC_init_default   {0, 0, 0, 0, 0}
#define IrqAllocMessageSimple_init_default       {0, 0, 0}
#define IrqAllocMessage_init_default             {0, {IrqAllocMessagex86_MSI_init_default}}
#define IOPortMessage_init_default               {0, 0}
#define ReturnMessage_init_default               {0, 0}
#define RpcMessage_init_default                  {0, {ReturnMessage_init_default}}
#define MemoryAllocMessage_init_zero             {0, 0, 0, _Action_MIN}
#define IrqAllocMessagex86_MSI_init_zero         {0, 0, 0, 0, 0}
#define IrqAllocMessagex86_IOAPIC_init_zero      {0, 0, 0, 0, 0}
#define IrqAllocMessageSimple_init_zero          {0, 0, 0}
#define IrqAllocMessage_init_zero                {0, {IrqAllocMessagex86_MSI_init_zero}}
#define IOPortMessage_init_zero                  {0, 0}
#define ReturnMessage_init_zero                  {0, 0}
#define RpcMessage_init_zero                     {0, {ReturnMessage_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define IOPortMessage_start_tag                  1
#define IOPortMessage_end_tag                    2
#define IrqAllocMessageSimple_setTrigger_tag     1
#define IrqAllocMessageSimple_irq_tag            2
#define IrqAllocMessageSimple_trigger_tag        3
#define IrqAllocMessagex86_IOAPIC_ioapic_tag     1
#define IrqAllocMessagex86_IOAPIC_pin_tag        2
#define IrqAllocMessagex86_IOAPIC_level_tag      3
#define IrqAllocMessagex86_IOAPIC_polarity_tag   4
#define IrqAllocMessagex86_IOAPIC_vector_tag     5
#define IrqAllocMessagex86_MSI_pci_bus_tag       1
#define IrqAllocMessagex86_MSI_pci_dev_tag       2
#define IrqAllocMessagex86_MSI_pci_func_tag      3
#define IrqAllocMessagex86_MSI_handle_tag        4
#define IrqAllocMessagex86_MSI_vector_tag        5
#define MemoryAllocMessage_address_tag           1
#define MemoryAllocMessage_size_bits_tag         2
#define MemoryAllocMessage_type_tag              3
#define MemoryAllocMessage_action_tag            4
#define ReturnMessage_errorCode_tag              1
#define ReturnMessage_cookie_tag                 2
#define IrqAllocMessage_msi_tag                  1
#define IrqAllocMessage_ioapic_tag               2
#define IrqAllocMessage_simple_tag               3
#define RpcMessage_ret_tag                       1
#define RpcMessage_memory_tag                    2
#define RpcMessage_irq_tag                       3
#define RpcMessage_ioport_tag                    4

/* Struct field encoding specification for nanopb */
#define MemoryAllocMessage_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT64, address, 1) \
X(a, STATIC, SINGULAR, UINT64, size_bits, 2) \
X(a, STATIC, SINGULAR, UINT64, type, 3) \
X(a, STATIC, SINGULAR, UENUM, action, 4)
#define MemoryAllocMessage_CALLBACK NULL
#define MemoryAllocMessage_DEFAULT NULL

#define IrqAllocMessagex86_MSI_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT64, pci_bus, 1) \
X(a, STATIC, SINGULAR, UINT64, pci_dev, 2) \
X(a, STATIC, SINGULAR, UINT64, pci_func, 3) \
X(a, STATIC, SINGULAR, UINT64, handle, 4) \
X(a, STATIC, SINGULAR, UINT64, vector, 5)
#define IrqAllocMessagex86_MSI_CALLBACK NULL
#define IrqAllocMessagex86_MSI_DEFAULT NULL

#define IrqAllocMessagex86_IOAPIC_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT64, ioapic, 1) \
X(a, STATIC, SINGULAR, UINT64, pin, 2) \
X(a, STATIC, SINGULAR, UINT64, level, 3) \
X(a, STATIC, SINGULAR, UINT64, polarity, 4) \
X(a, STATIC, SINGULAR, UINT64, vector, 5)
#define IrqAllocMessagex86_IOAPIC_CALLBACK NULL
#define IrqAllocMessagex86_IOAPIC_DEFAULT NULL

#define IrqAllocMessageSimple_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, BOOL, setTrigger, 1) \
X(a, STATIC, SINGULAR, UINT64, irq, 2) \
X(a, STATIC, SINGULAR, UINT64, trigger, 3)
#define IrqAllocMessageSimple_CALLBACK NULL
#define IrqAllocMessageSimple_DEFAULT NULL

#define IrqAllocMessage_FIELDLIST(X, a) \
X(a, STATIC, ONEOF, MESSAGE, (type,msi,type.msi), 1) \
X(a, STATIC, ONEOF, MESSAGE, (type,ioapic,type.ioapic), 2) \
X(a, STATIC, ONEOF, MESSAGE, (type,simple,type.simple), 3)
#define IrqAllocMessage_CALLBACK NULL
#define IrqAllocMessage_DEFAULT NULL
#define IrqAllocMessage_type_msi_MSGTYPE IrqAllocMessagex86_MSI
#define IrqAllocMessage_type_ioapic_MSGTYPE IrqAllocMessagex86_IOAPIC
#define IrqAllocMessage_type_simple_MSGTYPE IrqAllocMessageSimple

#define IOPortMessage_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, start, 1) \
X(a, STATIC, SINGULAR, UINT32, end, 2)
#define IOPortMessage_CALLBACK NULL
#define IOPortMessage_DEFAULT NULL

#define ReturnMessage_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, errorCode, 1) \
X(a, STATIC, SINGULAR, UINT64, cookie, 2)
#define ReturnMessage_CALLBACK NULL
#define ReturnMessage_DEFAULT NULL

#define RpcMessage_FIELDLIST(X, a) \
X(a, STATIC, ONEOF, MESSAGE, (msg,ret,msg.ret), 1) \
X(a, STATIC, ONEOF, MESSAGE, (msg,memory,msg.memory), 2) \
X(a, STATIC, ONEOF, MESSAGE, (msg,irq,msg.irq), 3) \
X(a, STATIC, ONEOF, MESSAGE, (msg,ioport,msg.ioport), 4)
#define RpcMessage_CALLBACK NULL
#define RpcMessage_DEFAULT NULL
#define RpcMessage_msg_ret_MSGTYPE ReturnMessage
#define RpcMessage_msg_memory_MSGTYPE MemoryAllocMessage
#define RpcMessage_msg_irq_MSGTYPE IrqAllocMessage
#define RpcMessage_msg_ioport_MSGTYPE IOPortMessage

extern const pb_msgdesc_t MemoryAllocMessage_msg;
extern const pb_msgdesc_t IrqAllocMessagex86_MSI_msg;
extern const pb_msgdesc_t IrqAllocMessagex86_IOAPIC_msg;
extern const pb_msgdesc_t IrqAllocMessageSimple_msg;
extern const pb_msgdesc_t IrqAllocMessage_msg;
extern const pb_msgdesc_t IOPortMessage_msg;
extern const pb_msgdesc_t ReturnMessage_msg;
extern const pb_msgdesc_t RpcMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MemoryAllocMessage_fields &MemoryAllocMessage_msg
#define IrqAllocMessagex86_MSI_fields &IrqAllocMessagex86_MSI_msg
#define IrqAllocMessagex86_IOAPIC_fields &IrqAllocMessagex86_IOAPIC_msg
#define IrqAllocMessageSimple_fields &IrqAllocMessageSimple_msg
#define IrqAllocMessage_fields &IrqAllocMessage_msg
#define IOPortMessage_fields &IOPortMessage_msg
#define ReturnMessage_fields &ReturnMessage_msg
#define RpcMessage_fields &RpcMessage_msg

/* Maximum encoded size of messages (where known) */
#define MemoryAllocMessage_size                  35
#define IrqAllocMessagex86_MSI_size              55
#define IrqAllocMessagex86_IOAPIC_size           55
#define IrqAllocMessageSimple_size               24
#define IrqAllocMessage_size                     57
#define IOPortMessage_size                       12
#define ReturnMessage_size                       17
#define RpcMessage_size                          59

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
