/*
 * Copyright 2019, Data61
 * Commonwealth Scientific and Industrial Research Organisation (CSIRO)
 * ABN 41 687 119 230.
 *
 * This software may be distributed and modified according to the terms of
 * the GNU General Public License version 2. Note that NO WARRANTY is provided.
 * See "LICENSE_GPLv2.txt" for details.
 *
 * @TAG(DATA61_GPL)
 */
/*
 * This file is autogenerated by kernel/tools/hardware_gen.py
 */

#pragma once

#include <types.h>
#include <psci.h>

#define MAX_NUM_REGIONS 1

struct elfloader_driver;

struct elfloader_device {
    const char *compat;
    volatile void *region_bases[MAX_NUM_REGIONS];
    struct elfloader_driver *drv;
};

struct elfloader_cpu {
    const char *compat;
    const char *enable_method;
    word_t cpu_id;
    word_t extra_data;
};

#ifdef DRIVER_COMMON
struct elfloader_device elfloader_devices[] = {
    {
        /* /psci */
        .compat = "arm,psci-1.0",
        .region_bases = {
            (void *)0,
        },
    },
    {
        /* /serial@ff1a0000 */
        .compat = "snps,dw-apb-uart",
        .region_bases = {
            (void *)0xff1a0000,
        },
    },
};

struct elfloader_cpu elfloader_cpus[] = {
    {
        /* /cpus/cpu@0 */
        .compat = "arm,cortex-a53",
        .enable_method = "psci",
        .cpu_id = 0x0,
        .extra_data = PSCI_METHOD_SMC
    },
    {
        /* /cpus/cpu@1 */
        .compat = "arm,cortex-a53",
        .enable_method = "psci",
        .cpu_id = 0x1,
        .extra_data = PSCI_METHOD_SMC
    },
    {
        /* /cpus/cpu@2 */
        .compat = "arm,cortex-a53",
        .enable_method = "psci",
        .cpu_id = 0x2,
        .extra_data = PSCI_METHOD_SMC
    },
    {
        /* /cpus/cpu@3 */
        .compat = "arm,cortex-a53",
        .enable_method = "psci",
        .cpu_id = 0x3,
        .extra_data = PSCI_METHOD_SMC
    },
    {
        /* /cpus/cpu@100 */
        .compat = "arm,cortex-a72",
        .enable_method = "psci",
        .cpu_id = 0x100,
        .extra_data = PSCI_METHOD_SMC
    },
    {
        /* /cpus/cpu@101 */
        .compat = "arm,cortex-a72",
        .enable_method = "psci",
        .cpu_id = 0x101,
        .extra_data = PSCI_METHOD_SMC
    },
    { .compat = NULL /* sentinel */ },
};
#else
extern struct elfloader_device elfloader_devices[];
extern struct elfloader_cpu elfloader_cpus[];
#endif