/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "rpc.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MemoryAllocMessage, MemoryAllocMessage, AUTO)


PB_BIND(IrqAllocMessagex86_MSI, IrqAllocMessagex86_MSI, AUTO)


PB_BIND(IrqAllocMessagex86_IOAPIC, IrqAllocMessagex86_IOAPIC, AUTO)


PB_BIND(IrqAllocMessageSimple, IrqAllocMessageSimple, AUTO)


PB_BIND(IrqAllocMessage, IrqAllocMessage, AUTO)


PB_BIND(IOPortMessage, IOPortMessage, AUTO)


PB_BIND(ReturnMessage, ReturnMessage, AUTO)


PB_BIND(RpcMessage, RpcMessage, AUTO)




/* @@protoc_insertion_point(eof) */
