/*
 * Copyright 2019, Data61
 * Commonwealth Scientific and Industrial Research Organisation (CSIRO)
 * ABN 41 687 119 230.
 *
 * This software may be distributed and modified according to the terms of
 * the GNU General Public License version 2. Note that NO WARRANTY is provided.
 * See "LICENSE_GPLv2.txt" for details.
 *
 * @TAG(DATA61_GPL)
 */
/*
 * This file is autogenerated by kernel/tools/hardware_gen.py.
 */

#ifndef __PLAT_DEVICES_GEN_H
#define __PLAT_DEVICES_GEN_H
#include <linker.h>

#ifndef KDEV_BASE
#include <mode/hardware.h>
#endif

#define physBase 0x10000000

/* INTERRUPTS */
/* INTERRUPT_VGIC_MAINTENANCE generated from /interrupt-controller@fee00000 */
#define INTERRUPT_VGIC_MAINTENANCE 25

/* KERNEL_TIMER_IRQ generated from /timer */
#ifdef CONFIG_ARM_HYPERVISOR_SUPPORT
#define KERNEL_TIMER_IRQ 26
#else
#define KERNEL_TIMER_IRQ 27
#endif /* CONFIG_ARM_HYPERVISOR_SUPPORT */

/* KERNEL DEVICES */
#define UART_PPTR (KDEV_BASE + 0x0)
#define GICD_PPTR (KDEV_BASE + 0x1000)
#define GICR_PPTR (KDEV_BASE + 0x11000)

#ifndef __ASSEMBLER__
static const kernel_frame_t BOOT_RODATA kernel_devices[] = {
    #ifdef CONFIG_PRINTING
    /* /serial@ff1a0000 */
    {
        0xff1a0000,
        UART_PPTR,
        true, /* armExecuteNever */
        true, /* userAvailable */
    },
    #endif /* CONFIG_PRINTING */
    /* /interrupt-controller@fee00000 */
    {
        0xfee00000,
        GICD_PPTR,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee01000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x2000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee02000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x3000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee03000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x4000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee04000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x5000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee05000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x6000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee06000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x7000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee07000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x8000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee08000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x9000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee09000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0xa000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee0a000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0xb000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee0b000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0xc000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee0c000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0xd000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee0d000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0xe000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee0e000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0xf000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfee0f000,
        /* contains GICD_PPTR */
        KDEV_BASE + 0x10000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    /* /interrupt-controller@fee00000 */
    {
        0xfef00000,
        GICR_PPTR,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef01000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x12000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef02000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x13000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef03000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x14000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef04000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x15000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef05000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x16000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef06000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x17000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef07000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x18000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef08000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x19000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef09000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x1a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef0a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x1b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef0b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x1c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef0c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x1d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef0d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x1e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef0e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x1f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef0f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x20000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef10000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x21000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef11000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x22000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef12000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x23000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef13000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x24000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef14000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x25000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef15000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x26000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef16000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x27000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef17000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x28000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef18000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x29000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef19000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x2a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef1a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x2b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef1b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x2c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef1c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x2d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef1d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x2e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef1e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x2f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef1f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x30000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef20000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x31000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef21000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x32000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef22000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x33000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef23000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x34000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef24000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x35000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef25000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x36000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef26000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x37000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef27000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x38000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef28000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x39000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef29000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x3a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef2a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x3b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef2b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x3c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef2c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x3d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef2d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x3e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef2e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x3f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef2f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x40000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef30000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x41000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef31000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x42000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef32000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x43000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef33000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x44000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef34000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x45000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef35000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x46000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef36000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x47000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef37000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x48000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef38000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x49000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef39000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x4a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef3a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x4b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef3b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x4c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef3c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x4d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef3d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x4e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef3e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x4f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef3f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x50000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef40000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x51000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef41000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x52000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef42000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x53000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef43000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x54000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef44000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x55000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef45000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x56000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef46000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x57000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef47000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x58000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef48000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x59000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef49000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x5a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef4a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x5b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef4b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x5c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef4c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x5d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef4d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x5e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef4e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x5f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef4f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x60000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef50000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x61000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef51000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x62000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef52000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x63000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef53000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x64000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef54000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x65000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef55000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x66000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef56000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x67000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef57000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x68000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef58000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x69000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef59000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x6a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef5a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x6b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef5b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x6c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef5c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x6d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef5d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x6e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef5e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x6f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef5f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x70000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef60000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x71000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef61000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x72000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef62000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x73000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef63000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x74000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef64000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x75000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef65000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x76000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef66000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x77000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef67000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x78000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef68000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x79000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef69000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x7a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef6a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x7b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef6b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x7c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef6c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x7d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef6d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x7e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef6e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x7f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef6f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x80000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef70000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x81000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef71000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x82000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef72000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x83000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef73000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x84000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef74000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x85000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef75000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x86000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef76000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x87000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef77000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x88000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef78000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x89000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef79000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x8a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef7a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x8b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef7b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x8c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef7c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x8d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef7d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x8e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef7e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x8f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef7f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x90000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef80000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x91000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef81000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x92000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef82000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x93000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef83000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x94000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef84000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x95000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef85000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x96000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef86000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x97000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef87000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x98000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef88000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x99000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef89000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x9a000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef8a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x9b000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef8b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x9c000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef8c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x9d000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef8d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x9e000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef8e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0x9f000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef8f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa0000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef90000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa1000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef91000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa2000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef92000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa3000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef93000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa4000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef94000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa5000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef95000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa6000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef96000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa7000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef97000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa8000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef98000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xa9000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef99000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xaa000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef9a000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xab000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef9b000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xac000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef9c000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xad000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef9d000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xae000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef9e000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xaf000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfef9f000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb0000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa0000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb1000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa1000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb2000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa2000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb3000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa3000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb4000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa4000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb5000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa5000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb6000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa6000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb7000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa7000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb8000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa8000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xb9000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefa9000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xba000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefaa000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xbb000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefab000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xbc000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefac000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xbd000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefad000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xbe000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefae000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xbf000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefaf000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc0000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb0000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc1000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb1000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc2000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb2000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc3000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb3000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc4000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb4000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc5000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb5000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc6000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb6000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc7000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb7000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc8000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb8000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xc9000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefb9000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xca000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefba000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xcb000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefbb000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xcc000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefbc000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xcd000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefbd000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xce000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefbe000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xcf000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
    {
        0xfefbf000,
        /* contains GICR_PPTR */
        KDEV_BASE + 0xd0000,
        true, /* armExecuteNever */
        false, /* userAvailable */
    },
};

/* PHYSICAL MEMORY */
static const p_region_t BOOT_RODATA avail_p_regs[] = {
    { 0x10000000, 0xf8000000 }, /* /memory@00000000 */
};

#endif /* !__ASSEMBLER__ */

#endif /* __PLAT_DEVICES_GEN_H */